spring:
  application:
    name: tweening-service
  profiles:
    active: dev

server:
  port: 8086

auth-service:
  url: http://auth-service:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized