import InsightCard from "@/components/ai-service/InsightCard";
import { ErrorDisplay } from "@/components/shared/ErrorDisplay";
import { NoData } from "@/components/shared/NoData";
import { LoadingSpinner } from "@/components/spinners/LoadingSpinner";
import { NotReadyPage } from "@/components/tasks-service/NotReadPage";
import { TaskHeader } from "@/components/tasks-service/TaskHeader";
import { useSelectedMeeting } from "@/hooks/task-service/useSelectedMeeting";
import { useAuth } from "@/hooks/useAuth";
import { snapshotToAiContext } from "@/lib/mappers/snapshotToContext";
import { formatDate } from "@/lib/utils";
import { useAiInsightStore } from "@/store/aiStore";
import { useContextStore } from "@/store/contextStore";
import { AiInsight } from "@/types/ai-service";
import { MeetingSnapshot } from "@/types/context-service";
import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";

export const Route = createFileRoute("/tasks/insights")({
  component: InsightsDashboard,
});

function InsightsDashboard() {
  const [filterSeverity, setFilterSeverity] = useState<
    AiInsight["severity"] | "ALL"
  >("ALL");
  const [searchTerm, setSearchTerm] = useState("");
  const { contextId, isReady, selectedMeeting } = useSelectedMeeting();
  const { meetingSnapshot, fetchMeetingSnapshot } = useContextStore();
  const {
    taskAnalysis,
    taskAnalysisLoading,
    taskAnalysisError,
    fetchTaskAnalysis,
  } = useAiInsightStore();
  const { user } = useAuth();

  useEffect(() => {
    if (contextId == null) return;
    fetchMeetingSnapshot(contextId);
  }, [fetchMeetingSnapshot, contextId]);

  useEffect(() => {
    const snapshot = meetingSnapshot[0];
    if (!snapshot) return;

    const enrichedSnapshot: MeetingSnapshot = {
      ...snapshot,
      generalMeetingDetails: {
        ...snapshot.generalMeetingDetails,
        ...selectedMeeting,
      },
    };
    const context = snapshotToAiContext(enrichedSnapshot);
    fetchTaskAnalysis(context);
  }, [meetingSnapshot, fetchTaskAnalysis, selectedMeeting]);

  const data = taskAnalysis;

  if (taskAnalysisLoading)
    // return <LoadingSpinner label='Getting Insights.......' fullScreen />;
    return (
      <div className='min-h-screen bg-background'>
        <TaskHeader userId={user?.id} userName={user?.displayName} />
        <LoadingSpinner label='Getting Insights.......' />;
      </div>
    );

  if (data == null)
    return (
      <div className='min-h-screen bg-background'>
        <TaskHeader userId={user?.id} userName={user?.displayName} />
        <NoData
          title='No Insights'
          description='Come back later!'
          icon='folder'
        />
      </div>
    );

  if (taskAnalysisError != null)
    return (
      <div className='min-h-screen bg-background'>
        <TaskHeader userId={user?.id} userName={user?.displayName} />
        <ErrorDisplay
          title='Error analysing tasks.'
          message={taskAnalysisError}
          variant='default'
        />
      </div>
    );

  const filteredInsights = data.insights.filter((insight) => {
    const matchesSeverity =
      filterSeverity === "ALL" || insight.severity === filterSeverity;
    const matchesSearch =
      searchTerm === "" ||
      insight.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      insight.detail.toLowerCase().includes(searchTerm.toLowerCase()) ||
      insight.category.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesSeverity && matchesSearch;
  });

  const highCount = data.insights.filter((i) => i.severity === "HIGH").length;
  const mediumCount = data.insights.filter(
    (i) => i.severity === "MEDIUM",
  ).length;
  const lowCount = data.insights.filter((i) => i.severity === "LOW").length;

  if (!isReady) {
    return (
      <NotReadyPage
        userId={user?.id}
        userName={user?.displayName}
        title='No Meeting Selected'
        description='select a meeting from the dropdown above to see insights'
      />
    );
  }

  return (
    <div className='min-h-screen bg-background'>
      <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12'>
        {/* Header Section */}
        <div className='space-y-6 mb-8'>
          {/* TaskHeader - Top row */}
          <TaskHeader userId={user?.id} userName={user?.displayName} />

          {/* Second Row: Title and Stats */}
          <div className='flex flex-col md:flex-row md:items-center md:justify-between gap-4'>
            {/* Title and meta info */}
            <div className='space-y-2'>
              <div className='flex items-center gap-3'>
                <h1 className='text-2xl md:text-3xl font-heading font-bold text-foreground'>
                  Insights
                </h1>
              </div>
              <p className='text-sm text-muted-foreground font-body'>
                Generated by{" "}
                <span className='font-mono text-primary'>{data.model}</span> on{" "}
                {formatDate(data.generatedAt)}
              </p>
            </div>

            {/* Severity Stats Cards */}
            <div className='flex gap-3'>
              <div className='px-4 py-2 rounded-lg bg-surface border border-border text-center min-w-20'>
                <div className='text-xs font-semibold text-destructive uppercase tracking-wide'>
                  HIGH
                </div>
                <div className='text-2xl font-bold text-destructive'>
                  {highCount}
                </div>
              </div>
              <div className='px-4 py-2 rounded-lg bg-surface border border-border text-center min-w-20'>
                <div className='text-xs font-semibold text-chart-4 uppercase tracking-wide'>
                  MEDIUM
                </div>
                <div className='text-2xl font-bold text-chart-4'>
                  {mediumCount}
                </div>
              </div>
              <div className='px-4 py-2 rounded-lg bg-surface border border-border text-center min-w-20'>
                <div className='text-xs font-semibold text-chart-2 uppercase tracking-wide'>
                  LOW
                </div>
                <div className='text-2xl font-bold text-chart-2'>
                  {lowCount}
                </div>
              </div>
            </div>
          </div>

          {/* Summary Card with Glass Effect */}
          <div className='glass-panel rounded-xl p-5 glow-border'>
            <p className='text-foreground/90 text-md leading-relaxed font-body'>
              {data.summary}
            </p>
          </div>

          {/* Filters Section */}
          <div className='flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between'>
            <div className='flex gap-2 flex-wrap'>
              <button
                onClick={() => setFilterSeverity("ALL")}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                  filterSeverity === "ALL"
                    ? "bg-primary text-primary-foreground glow-border"
                    : "bg-surface text-foreground hover:bg-secondary border border-border"
                }`}
              >
                All ({data.insights.length})
              </button>
              <button
                onClick={() => setFilterSeverity("HIGH")}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                  filterSeverity === "HIGH"
                    ? "bg-destructive text-destructive-foreground glow-border"
                    : "bg-surface text-foreground hover:bg-secondary border border-border"
                }`}
              >
                High ({highCount})
              </button>
              <button
                onClick={() => setFilterSeverity("MEDIUM")}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                  filterSeverity === "MEDIUM"
                    ? "bg-chart-4 text-white glow-border"
                    : "bg-surface text-foreground hover:bg-secondary border border-border"
                }`}
              >
                Medium ({mediumCount})
              </button>
              <button
                onClick={() => setFilterSeverity("LOW")}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                  filterSeverity === "LOW"
                    ? "bg-chart-2 text-white glow-border"
                    : "bg-surface text-foreground hover:bg-secondary border border-border"
                }`}
              >
                Low ({lowCount})
              </button>
            </div>

            <div className='relative w-full sm:w-72'>
              <input
                type='text'
                placeholder='Search insights...'
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className='w-full pl-10 pr-4 py-2 rounded-lg bg-surface text-foreground placeholder:text-muted-foreground border border-border focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all duration-200'
              />
              <svg
                className='absolute left-3 top-2.5 h-4 w-4 text-muted-foreground'
                fill='none'
                stroke='currentColor'
                viewBox='0 0 24 24'
              >
                <path
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  strokeWidth={2}
                  d='M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z'
                />
              </svg>
            </div>
          </div>
        </div>

        {/* Insights List */}
        <div className='space-y-4'>
          {filteredInsights.length === 0 ? (
            <div className='glass-panel rounded-xl p-12 text-center'>
              <p className='text-muted-foreground'>
                No insights match your filters.
              </p>
            </div>
          ) : (
            filteredInsights.map((insight, index) => (
              <InsightCard key={index} insight={insight} />
            ))
          )}
        </div>
      </div>
    </div>
  );
}

export default InsightsDashboard;
