spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: context-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/context/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: task-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/tasks/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: meeting-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/meetings/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: tweening-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/tweening/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: groups-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/groups/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: ai-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST