spring.application.name=task-service
spring.datasource.url=jdbc:postgresql://localhost:5432/meet_up_tasks_db
spring.datasource.username=postgres
spring.datasource.password=cmdvscod511824

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
