/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TranscriptRouteImport } from './routes/transcript'
import { Route as TasksRefRouteImport } from './routes/tasks-ref'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MeetingContextRouteImport } from './routes/meeting-context'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as R2faSetupRouteImport } from './routes/2fa-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTagsRouteImport } from './routes/tasks/tags'
import { Route as TasksStatisticsRouteImport } from './routes/tasks/statistics'
import { Route as TasksGanttRouteImport } from './routes/tasks/gantt'
import { Route as TasksCategoriesRouteImport } from './routes/tasks/categories'
import { Route as TasksBoardRouteImport } from './routes/tasks/board'
import { Route as TasksBacklogRouteImport } from './routes/tasks/backlog'
import { Route as GroupsFormRouteImport } from './routes/groups_/form'
import { Route as GroupsGroupIdRouteImport } from './routes/groups_.$groupId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as GroupsGroupIdTransferRouteImport } from './routes/groups_.$groupId.transfer'
import { Route as GroupsGroupIdSplitRouteImport } from './routes/groups_.$groupId.split'
import { Route as GroupsGroupIdMergeRouteImport } from './routes/groups_.$groupId.merge'
import { Route as GroupsGroupIdAddMemberRouteImport } from './routes/groups_.$groupId.add-member'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptRoute = TranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRefRoute = TasksRefRouteImport.update({
  id: '/tasks-ref',
  path: '/tasks-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingContextRoute = MeetingContextRouteImport.update({
  id: '/meeting-context',
  path: '/meeting-context',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faSetupRoute = R2faSetupRouteImport.update({
  id: '/2fa-setup',
  path: '/2fa-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTagsRoute = TasksTagsRouteImport.update({
  id: '/tasks/tags',
  path: '/tasks/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksStatisticsRoute = TasksStatisticsRouteImport.update({
  id: '/tasks/statistics',
  path: '/tasks/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksGanttRoute = TasksGanttRouteImport.update({
  id: '/tasks/gantt',
  path: '/tasks/gantt',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCategoriesRoute = TasksCategoriesRouteImport.update({
  id: '/tasks/categories',
  path: '/tasks/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksBoardRoute = TasksBoardRouteImport.update({
  id: '/tasks/board',
  path: '/tasks/board',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksBacklogRoute = TasksBacklogRouteImport.update({
  id: '/tasks/backlog',
  path: '/tasks/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsFormRoute = GroupsFormRouteImport.update({
  id: '/groups_/form',
  path: '/groups/form',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups_/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdTransferRoute = GroupsGroupIdTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdSplitRoute = GroupsGroupIdSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdMergeRoute = GroupsGroupIdMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdAddMemberRoute = GroupsGroupIdAddMemberRouteImport.update({
  id: '/add-member',
  path: '/add-member',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2fa-setup': typeof R2faSetupRoute
  '/briefing': typeof BriefingRoute
  '/decisions': typeof DecisionsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph': typeof GraphRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/meeting-context': typeof MeetingContextRoute
  '/memory': typeof MemoryRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/summary': typeof SummaryRoute
  '/tasks-ref': typeof TasksRefRoute
  '/transcript': typeof TranscriptRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/form': typeof GroupsFormRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/categories': typeof TasksCategoriesRoute
  '/tasks/gantt': typeof TasksGanttRoute
  '/tasks/statistics': typeof TasksStatisticsRoute
  '/tasks/tags': typeof TasksTagsRoute
  '/groups/$groupId/add-member': typeof GroupsGroupIdAddMemberRoute
  '/groups/$groupId/merge': typeof GroupsGroupIdMergeRoute
  '/groups/$groupId/split': typeof GroupsGroupIdSplitRoute
  '/groups/$groupId/transfer': typeof GroupsGroupIdTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2fa-setup': typeof R2faSetupRoute
  '/briefing': typeof BriefingRoute
  '/decisions': typeof DecisionsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph': typeof GraphRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/meeting-context': typeof MeetingContextRoute
  '/memory': typeof MemoryRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/summary': typeof SummaryRoute
  '/tasks-ref': typeof TasksRefRoute
  '/transcript': typeof TranscriptRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/form': typeof GroupsFormRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/categories': typeof TasksCategoriesRoute
  '/tasks/gantt': typeof TasksGanttRoute
  '/tasks/statistics': typeof TasksStatisticsRoute
  '/tasks/tags': typeof TasksTagsRoute
  '/groups/$groupId/add-member': typeof GroupsGroupIdAddMemberRoute
  '/groups/$groupId/merge': typeof GroupsGroupIdMergeRoute
  '/groups/$groupId/split': typeof GroupsGroupIdSplitRoute
  '/groups/$groupId/transfer': typeof GroupsGroupIdTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2fa-setup': typeof R2faSetupRoute
  '/briefing': typeof BriefingRoute
  '/decisions': typeof DecisionsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph': typeof GraphRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/meeting-context': typeof MeetingContextRoute
  '/memory': typeof MemoryRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/summary': typeof SummaryRoute
  '/tasks-ref': typeof TasksRefRoute
  '/transcript': typeof TranscriptRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/groups_/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups_/form': typeof GroupsFormRoute
  '/tasks/backlog': typeof TasksBacklogRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/categories': typeof TasksCategoriesRoute
  '/tasks/gantt': typeof TasksGanttRoute
  '/tasks/statistics': typeof TasksStatisticsRoute
  '/tasks/tags': typeof TasksTagsRoute
  '/groups_/$groupId/add-member': typeof GroupsGroupIdAddMemberRoute
  '/groups_/$groupId/merge': typeof GroupsGroupIdMergeRoute
  '/groups_/$groupId/split': typeof GroupsGroupIdSplitRoute
  '/groups_/$groupId/transfer': typeof GroupsGroupIdTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2fa-setup'
    | '/briefing'
    | '/decisions'
    | '/forgot-password'
    | '/graph'
    | '/groups'
    | '/login'
    | '/meeting'
    | '/meeting-context'
    | '/memory'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/summary'
    | '/tasks-ref'
    | '/transcript'
    | '/verify-email'
    | '/admin/users'
    | '/groups/$groupId'
    | '/groups/form'
    | '/tasks/backlog'
    | '/tasks/board'
    | '/tasks/categories'
    | '/tasks/gantt'
    | '/tasks/statistics'
    | '/tasks/tags'
    | '/groups/$groupId/add-member'
    | '/groups/$groupId/merge'
    | '/groups/$groupId/split'
    | '/groups/$groupId/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2fa-setup'
    | '/briefing'
    | '/decisions'
    | '/forgot-password'
    | '/graph'
    | '/groups'
    | '/login'
    | '/meeting'
    | '/meeting-context'
    | '/memory'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/summary'
    | '/tasks-ref'
    | '/transcript'
    | '/verify-email'
    | '/admin/users'
    | '/groups/$groupId'
    | '/groups/form'
    | '/tasks/backlog'
    | '/tasks/board'
    | '/tasks/categories'
    | '/tasks/gantt'
    | '/tasks/statistics'
    | '/tasks/tags'
    | '/groups/$groupId/add-member'
    | '/groups/$groupId/merge'
    | '/groups/$groupId/split'
    | '/groups/$groupId/transfer'
  id:
    | '__root__'
    | '/'
    | '/2fa-setup'
    | '/briefing'
    | '/decisions'
    | '/forgot-password'
    | '/graph'
    | '/groups'
    | '/login'
    | '/meeting'
    | '/meeting-context'
    | '/memory'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/summary'
    | '/tasks-ref'
    | '/transcript'
    | '/verify-email'
    | '/admin/users'
    | '/groups_/$groupId'
    | '/groups_/form'
    | '/tasks/backlog'
    | '/tasks/board'
    | '/tasks/categories'
    | '/tasks/gantt'
    | '/tasks/statistics'
    | '/tasks/tags'
    | '/groups_/$groupId/add-member'
    | '/groups_/$groupId/merge'
    | '/groups_/$groupId/split'
    | '/groups_/$groupId/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2faSetupRoute: typeof R2faSetupRoute
  BriefingRoute: typeof BriefingRoute
  DecisionsRoute: typeof DecisionsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GraphRoute: typeof GraphRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  MeetingRoute: typeof MeetingRoute
  MeetingContextRoute: typeof MeetingContextRoute
  MemoryRoute: typeof MemoryRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SummaryRoute: typeof SummaryRoute
  TasksRefRoute: typeof TasksRefRoute
  TranscriptRoute: typeof TranscriptRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminUsersRoute: typeof AdminUsersRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  GroupsFormRoute: typeof GroupsFormRoute
  TasksBacklogRoute: typeof TasksBacklogRoute
  TasksBoardRoute: typeof TasksBoardRoute
  TasksCategoriesRoute: typeof TasksCategoriesRoute
  TasksGanttRoute: typeof TasksGanttRoute
  TasksStatisticsRoute: typeof TasksStatisticsRoute
  TasksTagsRoute: typeof TasksTagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript': {
      id: '/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof TranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks-ref': {
      id: '/tasks-ref'
      path: '/tasks-ref'
      fullPath: '/tasks-ref'
      preLoaderRoute: typeof TasksRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-context': {
      id: '/meeting-context'
      path: '/meeting-context'
      fullPath: '/meeting-context'
      preLoaderRoute: typeof MeetingContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa-setup': {
      id: '/2fa-setup'
      path: '/2fa-setup'
      fullPath: '/2fa-setup'
      preLoaderRoute: typeof R2faSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tags': {
      id: '/tasks/tags'
      path: '/tasks/tags'
      fullPath: '/tasks/tags'
      preLoaderRoute: typeof TasksTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/statistics': {
      id: '/tasks/statistics'
      path: '/tasks/statistics'
      fullPath: '/tasks/statistics'
      preLoaderRoute: typeof TasksStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/gantt': {
      id: '/tasks/gantt'
      path: '/tasks/gantt'
      fullPath: '/tasks/gantt'
      preLoaderRoute: typeof TasksGanttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/categories': {
      id: '/tasks/categories'
      path: '/tasks/categories'
      fullPath: '/tasks/categories'
      preLoaderRoute: typeof TasksCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/board': {
      id: '/tasks/board'
      path: '/tasks/board'
      fullPath: '/tasks/board'
      preLoaderRoute: typeof TasksBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/backlog': {
      id: '/tasks/backlog'
      path: '/tasks/backlog'
      fullPath: '/tasks/backlog'
      preLoaderRoute: typeof TasksBacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups_/form': {
      id: '/groups_/form'
      path: '/groups/form'
      fullPath: '/groups/form'
      preLoaderRoute: typeof GroupsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups_/$groupId': {
      id: '/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups_/$groupId/transfer': {
      id: '/groups_/$groupId/transfer'
      path: '/transfer'
      fullPath: '/groups/$groupId/transfer'
      preLoaderRoute: typeof GroupsGroupIdTransferRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups_/$groupId/split': {
      id: '/groups_/$groupId/split'
      path: '/split'
      fullPath: '/groups/$groupId/split'
      preLoaderRoute: typeof GroupsGroupIdSplitRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups_/$groupId/merge': {
      id: '/groups_/$groupId/merge'
      path: '/merge'
      fullPath: '/groups/$groupId/merge'
      preLoaderRoute: typeof GroupsGroupIdMergeRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups_/$groupId/add-member': {
      id: '/groups_/$groupId/add-member'
      path: '/add-member'
      fullPath: '/groups/$groupId/add-member'
      preLoaderRoute: typeof GroupsGroupIdAddMemberRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdAddMemberRoute: typeof GroupsGroupIdAddMemberRoute
  GroupsGroupIdMergeRoute: typeof GroupsGroupIdMergeRoute
  GroupsGroupIdSplitRoute: typeof GroupsGroupIdSplitRoute
  GroupsGroupIdTransferRoute: typeof GroupsGroupIdTransferRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdAddMemberRoute: GroupsGroupIdAddMemberRoute,
  GroupsGroupIdMergeRoute: GroupsGroupIdMergeRoute,
  GroupsGroupIdSplitRoute: GroupsGroupIdSplitRoute,
  GroupsGroupIdTransferRoute: GroupsGroupIdTransferRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2faSetupRoute: R2faSetupRoute,
  BriefingRoute: BriefingRoute,
  DecisionsRoute: DecisionsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GraphRoute: GraphRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  MeetingRoute: MeetingRoute,
  MeetingContextRoute: MeetingContextRoute,
  MemoryRoute: MemoryRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SummaryRoute: SummaryRoute,
  TasksRefRoute: TasksRefRoute,
  TranscriptRoute: TranscriptRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminUsersRoute: AdminUsersRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  GroupsFormRoute: GroupsFormRoute,
  TasksBacklogRoute: TasksBacklogRoute,
  TasksBoardRoute: TasksBoardRoute,
  TasksCategoriesRoute: TasksCategoriesRoute,
  TasksGanttRoute: TasksGanttRoute,
  TasksStatisticsRoute: TasksStatisticsRoute,
  TasksTagsRoute: TasksTagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
